name: Accessible Grid
author: mashalla
category: Widgets
tags: [grid, htmltable, organisation, accessible]
#docs: http://www.accessiblemootoolsdemo.iao.fraunhofer.de/Mootools_Widgets/index.html
demo: http://www.accessiblemootoolsdemo.iao.fraunhofer.de/Mootools_Widgets/index.html
current: 1.2

sources:
  - "Source/grid.js"
  - "Source/demo.js"

